### ISSUE TITLE
I'm very sorry to ask you another question

### ISSUE THREAD

**Issue by dear1520** [codectile/crappy-esp#10]
I downloaded HLeaker and compiled it successfully, but I don't know how to use it to run the ESP program.
https://github.com/Schnocker/HLeaker

I think of several possibilities

![ka rt f5kqg4 _gkvug mh](https://user-images.githubusercontent.com/21070604/30782999-f0448056-a16e-11e7-84b4-6ece5b9f7afd.png)
YOUR_PROCESS "HLeaker.exe" modify "ESP"?

**Comment by dear1520** [comment]
Or execute the following code in CMD
![hil4b zi lxxvid ri](https://user-images.githubusercontent.com/21070604/30783038-880d7a64-a16f-11e7-9f6c-55f2eaa3a4fe.png)

**Comment by dear1520** [comment]
No matter how I tried, ESP responded to PUBG, but it produced a blank window that could not show anything
![hhu57 n9y oz_ m m iey](https://user-images.githubusercontent.com/21070604/30783082-101d57f8-a170-11e7-8d27-f3f99d0092cf.png)

**Comment by dear1520** [comment]
The state of the ESP operation

![wte6 tfinqvk0phv w e](https://user-images.githubusercontent.com/21070604/30783106-532edabc-a170-11e7-8907-59b36dc0c6ac.png)

**Comment by dear1520** [comment]
I know the general implementation principle here, whether or not to use HLeaker to get the handle of PUBG, and then pass the handle into ESP
But I don't know how to pass the handle into ESP
![wb227 e x loqa p3rrm5](https://user-images.githubusercontent.com/21070604/30783151-c4a02e1c-a170-11e7-9f18-14eeff5f5c20.png)

**Comment by dear1520** [comment]
So sorry,And Thanks

**Comment by codectile** [comment]
You just have to edit YOIR_PROCESS to your executable's name, that's all. Make sure to update world and gnames offset.

**Comment by dear1520** [comment]
![4ov q2d go4_ hjc7 sd 8](https://user-images.githubusercontent.com/21070604/30783956-b13ca8ec-a17e-11e7-932d-024e5434952d.png)
I tried to do this before, but HLeaker crashed when TslGame.exe was running
