### ISSUE TITLE
I tried to do this before, but HLeaker crashed when TslGame.exe was running

### ISSUE THREAD

**Issue by dear1520** [codectile/crappy-esp#11]
![4ov q2d go4_ hjc7 sd 8](https://user-images.githubusercontent.com/21070604/30784032-c4d6799a-a17f-11e7-9950-5405fa8e8728.png)
I tried to do this before, but HLeaker crashed when TslGame.exe was running
If you run before TslGame.exe, HLeakers won't crash, but at the same time, when should I open the crappy-esp program?.
If you do not use CMD to execute the crappy-esp program, the crappy-esp will crash.
Can you give me some screenshots of the crappy-esp running successfully?
I can take this as a reference
Thanks.

**Comment by codectile** [comment]
crappy-esp and hleaker should be in the same folder and both should be built for x64. Run the game then start hleaker.

**Comment by dear1520** [comment]
I did it, HLeaker worked, but it didn't work in the game
![5 _hk_ 4 43iwb9puqx4 9](https://user-images.githubusercontent.com/21070604/30784238-535cf21c-a184-11e7-9bc4-336386d8a2ed.png)

**Comment by dear1520** [comment]
Crappy-esp creates a blank window that cannot be displayed on the desktop and has no function in the game

**Comment by dear1520** [comment]
![hhu57 n9y oz_ m m iey](https://user-images.githubusercontent.com/21070604/30784255-a1053c90-a184-11e7-871c-8224c4776a26.png)
Like This

**Comment by dear1520** [comment]
Is it because the Crappy-esp compiler is having problems?

**Comment by codectile** [comment]
Update world and gnames offset and it will work. Press 1 for player esp, 2 for loot, 3 for vehicle.
