### ISSUE TITLE
Thank you for your patience, but I don't know how to Update world and games offset

### ISSUE THREAD

**Issue by dear1520** [codectile/crappy-esp#12]
First of all, thank you very much for your patience
But I don't know how to Update world and games offset
I've done a lot of trying
But none of them worked
I read the source code carefully， found a place worth paying attention to
![35 kk 100426bc 2 7x r9](https://user-images.githubusercontent.com/21070604/30784698-f15042fa-a18c-11e7-9dcd-5fb9faa7658f.png)

Many key judgments are related to UnrealWindow，If it needs the window name of the game，But I don't know how to get it.
Press 1 2 3 is nothing happen

**Comment by codectile** [comment]
please don't spam issues section. place a post on my thread in the forums.
