### ISSUE TITLE
need help, thx ,a compiling mistake

### ISSUE THREAD

**Issue by willerhehehe** [codectile/crappy-esp#16]
![360 20171019172807012](https://user-images.githubusercontent.com/32084498/31764137-e473ddde-b4f2-11e7-908f-ce9aed473e8d.png)

![image](https://user-images.githubusercontent.com/32084498/31763895-3ded0e68-b4f2-11e7-8c00-05defcedfc00.png)

I'v tried much time ,and don't konw how to slove this problem
I'v already  added dwmapi.h and dwmapi.lib,but it didn't work.

**Comment by codectile** [comment]
adding dwmapi.lib in properties->linker->input->additional dependencies, should do the work
