### ISSUE TITLE
You should not put it in GitHub, you should be ashamed of it.

### ISSUE THREAD

**Issue by liuziangexit** [codectile/crappy-esp#19]

**Comment by fakersaber** [comment]
Why? This is just plain source code, and you want this program to run, at least by bypassing battle eye, and that makes us learn a lot more.

**Comment by codectile** [comment]
i don't feel ashamed spreading knowledge

**Comment by liuziangexit** [comment]
yes, thats right. but this is a multiplayer game hack program, this thing will make other player feels bad. at least you should not put it in github or make business with this. and the developer still has the right to sue you.

**Comment by codectile** [comment]
this game uses one of the best anti-cheats, the developers should consider it as a challenge than a threat and I don't want to disrespect you but please stop posting useless butthurt comments. The issues section is for query about the code
