### ISSUE TITLE
error compile 2 ^^

### ISSUE THREAD

**Issue by bastien83720** [codectile/crappy-esp#3]
hello there is new somme error
![capture](https://user-images.githubusercontent.com/10518667/30594329-ecf0f472-9d4d-11e7-8ad6-68302b7c6a79.PNG)

**Comment by codectile** [comment]
you need to download directx sdk (november 2009) version and then link all the static libraries(d3d9.lib, d3dx9.lib) to your program.

**Comment by bastien83720** [comment]
do you have any discord or teamspeak to trade i have a cheat to

**Comment by bastien83720** [comment]
there is no sdk november 2009

**Comment by bastien83720** [comment]
![capture](https://user-images.githubusercontent.com/10518667/30595428-7cb91776-9d51-11e7-99c0-ba7322739ebb.PNG)

**Comment by codectile** [comment]
2008, sorry

**Comment by bastien83720** [comment]
not working

**Comment by codectile** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ee663275(v=vs.85).aspx
