### ISSUE TITLE
Hi~,some question

### ISSUE THREAD

**Issue by SentDz** [codectile/crappy-esp#4]

**Comment by SentDz** [comment]
Does this program start with the command line using HLeaker forged handles as arguments?

**Comment by SentDz** [comment]
`if (EnumProcessModulesEx(hProc, hMods, sizeof(hMods), &cb, LIST_MODULES_ALL))``

I made a mistake in this code

the HANDLE hProc is 0000000000000A04

HLeaker Process Handle : 0000000000000A04

please help me ^ ^

**Comment by SentDz** [comment]
I'm still looking for the problem


An exception was raised: read access rights conflict.
_First is nullptr。

For this code： if (EnumProcessModulesEx(hProc, hMods, sizeof(hMods), &cb, LIST_MODULES_ALL))`
iosfw.h

It looks like the problem with a person in the Forum

**Comment by SentDz** [comment]
I'm crazy ........

**Comment by codectile** [comment]
goto hleaker's source, find TARGET_PROCESS and YOUR_PROCESS defines and set them as TslGame.exe and `yourcheatname.exe` . compile it. place hleaker.exe and yourcheatname.exe in the same folder and start hleaker while the game is running.

**Comment by SentDz** [comment]
yourcheatname.exe means any exe?
or the crappy?

Are you interested in making money in China? The game is very popular in our country now. The average price is $228 / month

**Comment by SentDz** [comment]
thanks ！
I think I have more than half of my success
the CMD display Base Address: 0x7FF7F8730000

But However, an empty pointer error occurred
An exception was raised: read access rights conflict.
_First is nullptr。

For this code： if (EnumProcessModulesEx(hProc, hMods, sizeof(hMods), &cb, LIST_MODULES_ALL))`
iosfw.h
this problem

Do I have to re find the offset?

**Comment by SentDz** [comment]
Can you give me your skype or email？
I need to sleep ，It's 1 p. m. China time

You should earn more dollars for your good programming skills^^

**Comment by codectile** [comment]
yourcheatname.exe means the name of your hack's module.
...and i need full error thingy to know what's wrong

i don't have skype, though you can join my discord channel [link](https://discord.gg/SzpM2Gf)

**Comment by SentDz** [comment]
I'm excited to see you on the news. I'm getting up right now. I'm downloading discord and registering my account
