### ISSUE TITLE
can't compile 

### ISSUE THREAD

**Issue by bozoweed** [codectile/crappy-esp#5]
hi this is my bug i have install sdk of directx 2008 and use visual studio 2015  but i can't compile it ( i have include lib and includes into my project ) can you help me ?

![wtf](https://user-images.githubusercontent.com/11362992/30673524-094393ec-9e74-11e7-97ae-465f3b66fe0e.PNG)

**Comment by codectile** [comment]
remove the `L` and compile for x64.

**Comment by dkqnflek** [comment]
hello .Can you tell me your skype?

codectile

**Comment by bozoweed** [comment]
i'm not use skype

**Comment by bozoweed** [comment]
@codectile the probleme is not solved ...
![wtf](https://user-images.githubusercontent.com/11362992/30685592-b624f704-9eb5-11e7-8d31-2761172550b8.PNG)

**Comment by VincentKosciuszko** [comment]
Wow if you have no idea on what you are doing just give up. All errors are pretty simple to resolve if you have the most basic knowledge in programmation.

**Comment by bozoweed** [comment]
it's include of my d3d9.lib etc in one of my header i have compiled it
but now i get one more probleme when the exe run , i will go to seen that later --'
