### ISSUE TITLE
hi,a question about hleaker'source 

### ISSUE THREAD

**Issue by pilot1949** [codectile/crappy-esp#7]
## hello,i have some question about how to run hleaker's source successfully!
when i debug hleaker's source,i can run the code below successfully
`
CurrentProcess = new Process::CProcess();
CurrentProcess->SetPrivilege(SE_DEBUG_NAME, true);
CurrentProcess->SetPrivilege(SE_TCB_NAME, true);
TargetProcess = new Process::CProcess(std::string(TARGET_PROCESS));
TargetProcess->Wait(DELAY_TO_WAIT);
TargetProcess->Open();
if (TargetProcess->IsValidProcess())
{
`
but when after run the code bolow,the 'Handles' have 0 element,to find the source code,i find the my code cannot access to push_back,i dont konw why.
`if (Process->IsValidProcess() && ServiceGetProcessId(Process, reinterpret_cast<HANDLE>(handle->Handle), &pId))
						{
							if (pId == ProcessId)
								handlelist.push_back(HANDLE_INFO(handle->ProcessId, reinterpret_cast<HANDLE>(handle->Handle)));	
						}`
could tell me why this occured?thanksss!

**Comment by codectile** [comment]
maybe hleaker's developer can help you, create an issue about this in his repository.
