### ISSUE TITLE
Hello, I met a problem in compiling

### ISSUE THREAD

**Issue by dear1520** [codectile/crappy-esp#9]
![_vu1 x4a 5y8lpyzlduqau](https://user-images.githubusercontent.com/21070604/30742724-16c55082-9fcd-11e7-8ad5-fb076ec926a3.png)

The value of argv[1]
 here is problematic, mostly nil, and if I modify it to the argv [ 0 ] program, it can run, but it generates a program similar to the terminal

**Comment by codectile** [comment]
Use hleaker to start your process.
